name: network_module_sample
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  logger: ^2.4.0  
  get_it: ^7.6.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  retrofit_generator: ^7.0.8
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true