name: base_feature
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  usecase: 
    path: ../../domain/usecase
  design_system:
    path: ../../shared/design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0