name: platform
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  persistent_foundation: 
    path: ../../core/persistence_foundation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0