name: base_domain
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  entity:
    path: ../entity
  platform:
    path: ../../shared/platform

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

resolution: workspace