name: bloc_clean_coding
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.1
  another_flushbar: ^1.12.30
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  freezed: ^2.4.7
  google_fonts: ^6.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true